services:
  vector_postgres:
    image: pgvector/pgvector:pg16
    container_name: vector_postgres
    restart: always
    environment:
      POSTGRES_DB: vectoragent
      POSTGRES_USER: vectoruser
      POSTGRES_PASSWORD: vectorpassword
    ports:
      - "5122:5432"
    volumes:
      - vector_postgres_data:/var/lib/postgresql/data
      - ./db/vector_migrations:/docker-entrypoint-initdb.d
    networks:
      - stock_net

  postgres:
    image: postgres:16-alpine
    container_name: stock_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Jakarta
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5121:5432"
    networks:
      - stock_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: stock_app
    restart: always
    env_file: .env
    environment:
      APP_ROOT: /app
      TZ: Asia/Jakarta
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - stock_net
    command: python scheduler.py

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: stock_streamlit
    restart: always
    env_file: .env
    environment:
      APP_ROOT: /app
      PYTHONPATH: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    networks:
      - stock_net
    command: streamlit run ui/app.py --server.port=8501 --server.address=0.0.0.0

  web_api:
    build:
      context: .
      dockerfile: web-backend/Dockerfile
    container_name: web_user_api
    restart: always
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env
    environment:
      - DB_HOST=stock_postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - TZ=Asia/Jakarta
    networks:
      - stock_net
    depends_on:
      postgres:
        condition: service_healthy

  web_frontend:
    build:
      context: ./web-frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://web_api:8000
    container_name: web_user_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://web_api:8000
      - TZ=Asia/Jakarta
    networks:
      - stock_net
    depends_on:
      - web_api

volumes:
  postgres_data:
  vector_postgres_data:

networks:
  stock_net:
    driver: bridge
