services:
  postgres:
    image: postgres:16-alpine
    container_name: stock_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5121:5432"
    networks:
      - stock_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: stock_app
    restart: always
    env_file: .env
    environment:
      APP_ROOT: /app
      PYTHONPATH: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - stock_net
    command: python scheduler.py

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: stock_streamlit
    restart: always
    env_file: .env
    environment:
      APP_ROOT: /app
      PYTHONPATH: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    networks:
      - stock_net
    command: streamlit run ui/app.py --server.port=8501 --server.address=0.0.0.0

volumes:
  postgres_data:

networks:
  stock_net:
    driver: bridge
