#!/bin/bash
# Quick start guide untuk Realtime Stockbit Integration

echo "=== Realtime Stockbit Integration - Quick Start ==="
echo ""
echo "✅ IMPLEMENTASI SELESAI"
echo ""
echo "File yang dimodifikasi/dibuat:"
echo "  1. data/fetcher_stockbit.py - Tambah get_ihsg_realtime_price_stockbit()"
echo "  2. web-backend/main.py - Update /api/ihsg endpoint"
echo "  3. agents/portfolio_advisor.py - Update analyze_portfolio() dengan realtime prices"
echo "  4. REALTIME_STOCKBIT_INTEGRATION.md - Dokumentasi lengkap"
echo "  5. test_realtime_integration.py - Test script"
echo ""
echo "=== TESTING ==="
echo ""
echo "Run test script:"
echo "  python test_realtime_integration.py"
echo ""
echo "=== API ENDPOINTS ==="
echo ""
echo "1. IHSG Realtime (baru)"
echo "   GET /api/ihsg"
echo "   Response sekarang include field 'realtime' dengan:"
echo "     - price (harga IHSG terbaru)"
echo "     - change (perubahan harga)"
echo "     - change_pct (persentase perubahan)"
echo "     - timestamp"
echo ""
echo "2. Portfolio Analysis (updated)"
echo "   POST /api/portfolio/ai-analysis"
echo "   - Sekarang fetch realtime prices untuk semua tickers"
echo "   - DCA Priority recommendations berbasis harga realtime"
echo "   - Target price & target lots akurat"
echo ""
echo "=== FITUR BARU ==="
echo ""
echo "✓ Realtime IHSG price dari Stockbit"
echo "✓ Realtime ticker prices (parallel fetch)"
echo "✓ Portfolio analysis dengan data terbaru"
echo "✓ Better recommendations berdasarkan market conditions"
echo "✓ Error handling & fallback jika Stockbit down"
echo ""
echo "=== NEXT STEPS ==="
echo ""
echo "1. Jalankan test script:"
echo "   python test_realtime_integration.py"
echo ""
echo "2. Test endpoint IHSG:"
echo "   curl -X GET http://localhost:8000/api/ihsg \\"
echo "     -H 'Authorization: Bearer <token>'"
echo ""
echo "3. Test portfolio analysis:"
echo "   curl -X POST http://localhost:8000/api/portfolio/ai-analysis \\"
echo "     -H 'Authorization: Bearer <token>' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{ ... }'"
echo ""
echo "=== TROUBLESHOOTING ==="
echo ""
echo "Jika test gagal:"
echo "  - Cek STOCKBIT_API_KEY di .env"
echo "  - Pastikan refresh token sudah valid"
echo "  - Check logs: tail -f app.log"
echo ""
