"""Add MlPredictionLog table

Revision ID: 2da5c590cc51
Revises: users_001
Create Date: 2026-07-24 07:13:30.977554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2da5c590cc51'
down_revision = 'users_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_prediction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('horizon', sa.String(length=5), nullable=False),
    sa.Column('pred_return_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('pred_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('actual_close_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_return_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'ticker', 'horizon', name='uix_ml_pred_date_ticker_hor')
    )
    op.drop_index('idx_scores_run_date', table_name='agent_scores')
    op.alter_column('broker_accumulation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_broker_ticker_date', table_name='broker_accumulation')
    op.alter_column('dca_strategy', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('dca_strategy', 'user_id')
    op.alter_column('dca_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('dca_transactions', 'user_id')
    op.alter_column('debate_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_debate_run_date', table_name='debate_logs')
    op.alter_column('ihsg_ohlcv', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_ihsg_ohlcv_date', table_name='ihsg_ohlcv')
    op.alter_column('ohlcv_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_ohlcv_ticker_date', table_name='ohlcv_prices')
    op.create_foreign_key(None, 'paper_wallet', 'users', ['user_id'], ['id'])
    op.alter_column('performance', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('portfolio_holdings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('portfolio_holdings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sector_ohlcv', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_sector_ohlcv_date', table_name='sector_ohlcv')
    op.alter_column('signals', 'weight_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index('idx_signals_run_date', table_name='signals')
    op.alter_column('stock_info_snapshot', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_stock_info_snap', table_name='stock_info_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_stock_info_snap', 'stock_info_snapshot', ['ticker', 'snapshot_date'], unique=False)
    op.alter_column('stock_info_snapshot', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_signals_run_date', 'signals', ['run_date'], unique=False)
    op.alter_column('signals', 'weight_mode',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('idx_sector_ohlcv_date', 'sector_ohlcv', ['sector_code', 'trade_date'], unique=False)
    op.alter_column('sector_ohlcv', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('portfolio_holdings', 'updated_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('portfolio_holdings', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('performance', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'paper_wallet', type_='foreignkey')
    op.create_index('idx_ohlcv_ticker_date', 'ohlcv_prices', ['ticker', 'trade_date'], unique=False)
    op.alter_column('ohlcv_prices', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_ihsg_ohlcv_date', 'ihsg_ohlcv', ['trade_date'], unique=False)
    op.alter_column('ihsg_ohlcv', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_debate_run_date', 'debate_logs', ['run_date', 'ticker'], unique=False)
    op.alter_column('debate_logs', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('dca_transactions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('dca_transactions', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('dca_strategy', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('dca_strategy', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_broker_ticker_date', 'broker_accumulation', ['ticker', 'trade_date'], unique=False)
    op.alter_column('broker_accumulation', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_scores_run_date', 'agent_scores', ['run_date', 'ticker'], unique=False)
    op.create_table('ihsg_no_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ihsg_no_data_pkey'),
    sa.UniqueConstraint('trade_date', name='ihsg_no_data_trade_date_key')
    )
    op.create_index('idx_ihsg_no_data_date', 'ihsg_no_data', ['trade_date'], unique=False)
    op.create_table('ohlcv_no_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), server_default=sa.text("'stockbit'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ohlcv_no_data_pkey'),
    sa.UniqueConstraint('ticker', 'trade_date', 'source', name='ohlcv_no_data_ticker_trade_date_source_key')
    )
    op.create_index('idx_ohlcv_no_data_ticker_date', 'ohlcv_no_data', ['ticker', 'trade_date'], unique=False)
    op.create_table('ihsg_predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('current_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('direction', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('volatility_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('day_1_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_1_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_3_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_3_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_5_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_5_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_7_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_7_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_drivers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ihsg_trend', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('macro_signal', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('accuracy_score', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ihsg_predictions_pkey')
    )
    op.create_index('idx_ihsg_run_date', 'ihsg_predictions', [sa.literal_column('run_date DESC')], unique=False)
    op.drop_table('ml_prediction_log')
    # ### end Alembic commands ###
