"""add tp columns

Revision ID: 4bbaa11f38cf
Revises: 
Create Date: 2026-06-07 13:38:07.751318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bbaa11f38cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ihsg_run_date', table_name='ihsg_predictions')
    op.drop_table('ihsg_predictions')
    op.alter_column('agent_scores', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_scores_run_date', table_name='agent_scores')
    op.alter_column('broker_accumulation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_broker_ticker_date', table_name='broker_accumulation')
    op.drop_column('broker_accumulation', 'broker_type')
    op.drop_column('broker_accumulation', 'day_foreign_net')
    op.alter_column('debate_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_debate_run_date', table_name='debate_logs')
    op.alter_column('ihsg_ohlcv', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_ihsg_ohlcv_date', table_name='ihsg_ohlcv')
    op.alter_column('ohlcv_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_ohlcv_ticker_date', table_name='ohlcv_prices')
    op.alter_column('performance', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sector_ohlcv', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_sector_ohlcv_date', table_name='sector_ohlcv')
    op.add_column('signals', sa.Column('target_3', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('signals', sa.Column('tp_position_sizing', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('signals', sa.Column('risk_reward_tp1', sa.String(length=20), nullable=True))
    op.add_column('signals', sa.Column('risk_reward_tp2', sa.String(length=20), nullable=True))
    op.add_column('signals', sa.Column('risk_reward_tp3', sa.String(length=20), nullable=True))
    op.alter_column('signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_signals_run_date', table_name='signals')
    op.alter_column('stock_info_snapshot', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_stock_info_snap', table_name='stock_info_snapshot')
    op.alter_column('universe', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('universe', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_stock_info_snap', 'stock_info_snapshot', ['ticker', 'snapshot_date'], unique=False)
    op.alter_column('stock_info_snapshot', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_signals_run_date', 'signals', ['run_date'], unique=False)
    op.alter_column('signals', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('signals', 'risk_reward_tp3')
    op.drop_column('signals', 'risk_reward_tp2')
    op.drop_column('signals', 'risk_reward_tp1')
    op.drop_column('signals', 'tp_position_sizing')
    op.drop_column('signals', 'target_3')
    op.create_index('idx_sector_ohlcv_date', 'sector_ohlcv', ['sector_code', 'trade_date'], unique=False)
    op.alter_column('sector_ohlcv', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('performance', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_ohlcv_ticker_date', 'ohlcv_prices', ['ticker', 'trade_date'], unique=False)
    op.alter_column('ohlcv_prices', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_ihsg_ohlcv_date', 'ihsg_ohlcv', ['trade_date'], unique=False)
    op.alter_column('ihsg_ohlcv', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_debate_run_date', 'debate_logs', ['run_date', 'ticker'], unique=False)
    op.alter_column('debate_logs', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('broker_accumulation', sa.Column('day_foreign_net', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('broker_accumulation', sa.Column('broker_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_index('idx_broker_ticker_date', 'broker_accumulation', ['ticker', 'trade_date'], unique=False)
    op.alter_column('broker_accumulation', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_scores_run_date', 'agent_scores', ['run_date', 'ticker'], unique=False)
    op.alter_column('agent_scores', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('ihsg_predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('current_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('direction', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('volatility_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('day_1_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_1_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_3_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_3_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_5_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_5_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_7_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('day_7_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_drivers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ihsg_trend', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('macro_signal', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ihsg_predictions_pkey')
    )
    op.create_index('idx_ihsg_run_date', 'ihsg_predictions', [sa.literal_column('run_date DESC')], unique=False)
    # ### end Alembic commands ###
