"""add candlestick_signals table

Revision ID: 663c30fb225e
Revises: 6df0c855cdfa
Create Date: 2026-07-27 08:15:51.020828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663c30fb225e'
down_revision = '6df0c855cdfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
