"""add backtest_sessions and backtest_results tables

Revision ID: 6df0c855cdfa
Revises: ensure_ihsg_tables
Create Date: 2026-07-25 07:33:42.664093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df0c855cdfa'
down_revision = 'ensure_ihsg_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('horizon', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('final_capital', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('final_capital', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('trades_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['backtest_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_ihsg_no_data_date', table_name='ihsg_no_data')
    op.drop_index('idx_ihsg_run_date', table_name='ihsg_predictions')
    op.alter_column('ml_prediction_log', 'pred_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('ml_prediction_log', 'actual_close_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('idx_ohlcv_no_data_ticker_date', table_name='ohlcv_no_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ohlcv_no_data_ticker_date', 'ohlcv_no_data', ['ticker', 'trade_date'], unique=False)
    op.alter_column('ml_prediction_log', 'actual_close_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('ml_prediction_log', 'pred_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.create_index('idx_ihsg_run_date', 'ihsg_predictions', [sa.literal_column('run_date DESC')], unique=False)
    op.create_index('idx_ihsg_no_data_date', 'ihsg_no_data', ['trade_date'], unique=False)
    op.drop_table('backtest_results')
    op.drop_table('backtest_sessions')
    # ### end Alembic commands ###
