"""add candlestick_signals table

Revision ID: 8f512f170146
Revises: 663c30fb225e
Create Date: 2026-07-27 08:17:11.571607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f512f170146'
down_revision = '663c30fb225e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candlestick_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('pattern_name', sa.String(length=100), nullable=False),
    sa.Column('signal_direction', sa.String(length=20), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('context_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_date', 'ticker', name='uq_candlestick_date_ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candlestick_signals')
    # ### end Alembic commands ###
